# Generated by Django 2.1.5 on 2019-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='text_field',
            field=models.TextField(verbose_name='Paste some text with kanji. Anything else will be ignored.'),
        ),
    ]
