# Generated by Django 2.1.5 on 2019-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetgen', '0002_auto_20190127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='text_field',
            field=models.TextField(help_text='Currently, we can only process about 300 characters at once because of free and weak web hosting.', verbose_name='Paste some text with kanji. Anything else will be ignored.'),
        ),
    ]
