# Generated by Django 2.1.5 on 2020-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetgen', '0003_auto_20190127_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='text_field',
            field=models.TextField(help_text='Currently, we can only process about 300 characters', verbose_name='Paste some text with kanji. Anything else will be ignored.'),
        ),
    ]
