# Generated by Django 2.1.5 on 2020-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetgen', '0005_auto_20200518_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='text_field',
            field=models.TextField(help_text='Currently, we can only process about 300 characters at once', verbose_name='Paste text with Kanji'),
        ),
    ]
